name: trading_simulator
description: An educational trading simulator app with real-time data

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  
  # HTTP & API
  http: ^1.1.2
  web_socket_channel: ^2.4.0
  
  # UI & Charts
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  fl_chart: ^0.66.0
  
  # Utilities
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.2.1
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  riverpod_lint: ^2.3.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/ 